#!/bin/bash
# Environment variables for CUDA/PyTorch compatibility
# Generated by fix_cuda.py

export CUDA_DEVICE_ORDER=PCI_BUS_ID
export CUBLAS_WORKSPACE_CONFIG=:4096:8
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128
export TORCH_USE_RTLD_GLOBAL=YES
export PYTORCH_ALLOW_NET_FALLBACK=1
